@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTczNzU4NDU0MSwiZXhwIjoxNzM3NTg4MTQxfQ.U_Ak3eJLkjsbY5JQrh9IP8_DTZZsqG5CGcGgfB6FRno
@BASE_URL = http://localhost:8000

###
POST {{BASE_URL}}/category
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "name": "Category"
}

###
GET {{BASE_URL}}/categories
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

###
PATCH  {{BASE_URL}}/category
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "name": "NewCategory"
}

###
DELETE  {{BASE_URL}}/category
Authorization: Bearer {{TOKEN}}
Content-Type: application/json
