@TOKEN =
@BASE_URL = http://localhost:8000

###
POST {{BASE_URL}}/category
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "name": "Category"
}

###
GET {{BASE_URL}}/categories
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

###
PATCH  {{BASE_URL}}/category
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "name": "NewCategory"
}

###
DELETE  {{BASE_URL}}/category
Authorization: Bearer {{TOKEN}}
Content-Type: application/json
