@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTczNzY3ODE5MCwiZXhwIjoxNzM3NjgxNzkwfQ.IqydFkyGfXI5DfRmE18uGpswcykxVDM9FiJ31fRpE5E
@BASE_URL = http://localhost:8000

###
POST {{BASE_URL}}/category
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "name": "Category"
}

###
GET {{BASE_URL}}/categories
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

###
PATCH  {{BASE_URL}}/category
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "name": "NewCategory"
}

###
DELETE  {{BASE_URL}}/category
Authorization: Bearer {{TOKEN}}
Content-Type: application/json
