@TOKEN = 
@BASE_URL = http://localhost:8000

###
POST {{BASE_URL}}/transaction
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "type": "INCOME",
    "amount": 1000,
    "categoryName": "Salário"
}
