@TOKEN =
@BASE_URL = http://localhost:8000

###
POST {{BASE_URL}}/transaction
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "type": "INCOME",
    "amount": 1000,
    "categoryName": "Salário",
    "date": "2025-01-01"
}

###
POST {{BASE_URL}}/transaction
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "type": "EXPENSE",
    "amount": 1000,
    "categoryName": "Salário",
    "date": "2025-01-01"
}

###
PATCH {{BASE_URL}}/transaction/update/
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "type": "EXPENSE",
    "amount": 5000,
    "categoryName": "Transporte",
    "date": "2025-12-01"
}

###
GET {{BASE_URL}}/transaction/balance?month=01&year=2025
Authorization: Bearer {{TOKEN}}
Content-Type: application/json
